config/routes.rb
require "silencer"

ChaosRails::Application.routes.draw do
  devise_for :users

  use_doorkeeper
  use_doorkeeper_openid_connect

  root to: "static#home"

  match "*path", to: "application#options", via: :options

  get "up" => "rails/health#show", as: :rails_health_check

  resources :events,      only: [ :index ]
  resources :shows,       only: [ :index, :show ]
  resources :workshops,   only: [ :index, :show ]
  resources :seasons,     only: [ :index, :show ]
  resources :news,        only: [ :index, :show ]
  resources :venues,      only: [ :index, :show ] do
    collection do
      get "map"
    end
  end

  resource :profile_completion, only: [ :show, :update ]

  resources :users, only: [ :show ] do
    member do
      put "consent"
    end

    collection do
      get "current", to: "users#current"
    end
  end

  get "marketing_creatives/sign_up", to: "admin/marketing_creatives/profiles#sign_up"

  COMPLAINTS_ALIASES.each do |path|
    get path, to: redirect("complaints/new")
  end

  resources :complaints, only: [ :new, :create ]

  get "attachments/:slug(/:style)", to: "attachments#file", as: "attachment"

  if Rails.env.test? || Rails.env.development?
    get "tests/test_500", to: "tests#test_500"
  end

  namespace :admin do
    get "", to: "dashboard#index"

    mount MissionControl::Jobs::Engine, at: "/jobs"

    get "resources", to: "resources#page", as: :resources_index
    get "resources/membership_checker", to: "resources#membership_checker", as: :resources_membership_checker
    get "resources/(*page)", to: "resources#page", as: :resources

    resources :events, only: [ :index, :show ] do
      member do
        get "xts", to: "events#find_by_xts_id"
      end

      collection do
        get "debt_overview"
      end
    end

    resources :shows do
      resources :feedbacks, except: [ :show ]

      resources :show_crew_imports, only: [ :new ] do
        collection do
          post :preview
          post :confirm
        end
      end

      collection do
        get "query_xts"
      end

      member do
        patch "update_debt_settings", to: "shows#update_debt_settings"
        get "xts_report"
        post "convert_to_season", to: "shows#convert_to_season"
        post "convert_to_workshop", to: "shows#convert_to_workshop"
      end
    end

    resources :workshops do
      resources :feedbacks, except: [ :show ]

      resources :show_crew_imports, only: [ :new ] do
        collection do
          post :preview
          post :confirm
        end
      end

      member do
        patch "update_debt_settings", to: "workshops#update_debt_settings"
      end
    end

    resources :seasons do
      resources :feedbacks, except: [ :show ]

      resources :show_crew_imports, only: [ :new ] do
        collection do
          post :preview
          post :confirm
        end
      end

      member do
        patch "update_debt_settings", to: "seasons#update_debt_settings"
      end
    end

    resources :debt_notifications, only: [ :index ]

    resources :staffing_debts, except: [ :destroy ] do
      member do
        put "convert_to_maintenance_debt"
        put "forgive"
      end
    end

    resources :maintenance_debts, except: [ :destroy ] do
      member do
        put "convert_to_staffing_debt"
        put "forgive"
      end
    end

    resources :debts

    resources :maintenance_sessions
    resources :maintenance_attendances

    resources :venues do
      collection do
        get "map"
      end
    end

    resources :news
    resources :fault_reports

    resources :event_tags
    resources :attachment_tags
    resources :picture_tags

    resources :attachments, only: [ :index ]
    resources :pictures, only: [ :index ]

    resources :opportunities do
      member do
        put "approve"
        put "reject"
      end
    end

    resources :membership, only: [] do
      collection do
        get "check_membership", to: "membership#check_membership"
      end
    end

    resources :editable_blocks
    resources :carousel_items
    resources :mass_mails

    resources :users do
      member do
        post "reset_password"
        get "merge"
        post "merge_preview"
        post "absorb"
      end

      collection do
        get  "activate", to: "users#activate"
        post "activate", to: "users#create_activation"
        post "resend_activation", to: "users#resend_activation"
        get  "autocomplete_list", constraints: { format: :json }
      end
    end

    resources :duplicates, only: [ :index ] do
      collection do
        post :mark_not_duplicate
      end
    end

    resources :membership_imports, only: [ :new ] do
      collection do
        post :preview
        post :confirm
      end
    end

    resources :user_imports, only: [ :new ] do
      collection do
        post :preview
        post :confirm
      end
    end

    resources :reviews

    resources :roles do
      member do
        post "add_user", to: "roles#add_user"
        delete "remove_user/:user_id", to: "roles#remove_user", as: "remove_user"
        delete "purge", to: "roles#purge"
        put "archive", to: "roles#archive"
      end
    end

    get  "/permissions/grid", to: "permissions#grid", as: :permissions
    post "/permissions/grid", to: "permissions#update_grid", as: :update_permissions

    resources :techies do
      collection do
        get "tree"
        get "bush"
        get "tree_data"
        get "mass_new"
        post "mass_create"
        get "by_entry_year"
      end
    end

    get "techie_families", to: "techies#index"

    namespace :marketing_creatives do
      resources :profiles do
        collection do
          get "sign_up", to: "profiles#sign_up"
        end

        member do
          put "approve"
          put "reject"
        end
      end

      resources "", controller: "categories", as: "categories"
    end

    resources :staffing_templates

    resources :staffings do
      collection do
        get ":slug/grid", to: "staffings#grid", format: :html, as: :grid
      end
    end

    get "/staffings/job/:id/sign_up_confirm", to: "staffings#sign_up_confirm", as: :sign_up_confirm
    put "/staffings/job/:id/sign_up", to: "staffings#sign_up", as: :staffing_sign_up

    get "/proposals", to: redirect("/admin/proposals/calls")
    namespace :proposals do
      resources :calls do
        member do
          put "archive"
        end

        resources :proposals, only: :index
      end

      resources :proposals, except: :index do
        member do
          put "approve"
          put "reject"
          put "convert"
        end
      end

      get "/about", to: "proposals#about"
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires do
        member do
          get  "answer", to: "questionnaires#answer"
          put "answer", to: "questionnaires#set_answers"
          patch "answer", to: "questionnaires#set_answers"
        end
      end

      resources :questionnaire_templates
    end

    get "tests", to: "tests#index"
    namespace :tests do
      get "test_alerts/:type", action: "test_alerts", as: "test_alerts"
      get "test_404"
      get "test_500"
      get "test_access_denied"
    end

    resources :complaints, except: [ :new, :create ] do
      get "new", to: redirect("/complaints/new")
    end

    get "/reports/", to: "reports#index", as: "reports"
    namespace "reports" do
      %w[roles members newsletter_subscribers staffing].each do |action|
        put action, action: action, as: action
      end
    end

    namespace "help" do
      %w[kramdown venue_location].each do |action|
        get action, action: action, as:  action, controller: "/admin/help"
      end
    end

    get "committee", to: "static#committee", as: :committee
    get "bootstrap_test", to: "static#bootstrap_test", as: :bootstrap_test
    get "*page", to: "static#error", as: :static

    if Rails.env.test? || Rails.env.development?
      get "dashboard/widget/:widget_name", to: "dashboard#widget"
    end
  end

  get "archives", to: "archives#index", as: :archives_index
  namespace :archives do
    get "events", to: "events#index", as: :events
    get "shows", to: "shows#index", as: :shows
    get "workshops", to: "workshops#index", as: :workshops
    get "proposals", to: "proposals#index", as: :proposals
    get "seasons",    to: "seasons#index",    as: :seasons
  end
  get "archives/(*page)", to: "archives#page", as: :archives

  post "markdown/preview", to: "markdown#preview"

  get "about", to: "about#page", as: :about_index
  get "about/(*page)", to: "about#page", as: :about

  get "get_involved", to: "get_involved#page", as: :get_involved_index
  get "get_involved/opportunities", to: "get_involved#opportunities", as: :get_involved_opportunities
  get "get_involved/(*page)", to: "get_involved#page", as: :get_involved

  get "youth", to: redirect("/getinvolved/youth_project")

  get "welcomeweek", to: redirect("/welcome_week")
  get "welcome_week/parapicnic_in_the_park", to: redirect("https://theatreparadok.co.uk/events/2021_09_parapicnic/")
  get "welcome_week/catching_up", to: redirect("https://theatreparadok.co.uk/events/catching-up-fringe-show-performance-screening-for-welcome-week/")

  get "welcome_week", to: redirect("get_involved/welcome_week")

  get "dev_auth/login", to: "dev_auth#login" if Rails.env.local?

  get "/:id", to: "seasons#show", constraints: Constraints::ExistingSeason.new

  get "/*page", to: "static#show", as: :static, constraints: lambda { |request|
    !request.path.starts_with?("/rails/active_storage") && !request.path.starts_with?("/assets")
  }

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::GenericEventsController
  include AcademicYearHelper

  # GET admin/shows/debt_overview
  def debt_overview
    authorize! :debt_overview, Event

    academic_year_start = start_of_year
    @shows = Event.where("end_date >= ?", academic_year_start)
                  .includes(:event_tags, :venue)
                  .order(start_date: :asc)
  end
end

app/controllers/archives/events_controller.rb
class Archives::EventsController < Archives::GenericEventsController
  def index
    super

    @title = "Event Archive"
    @url = :archives_events
  end
end

app/controllers/events_controller.rb
class EventsController < PublicGenericEventsController
  def find_by_xts_id
    @event = Event.find_by_xts_id(params[:id])

    # render json: @event.to_json(methods: [:slideshow_image_url], include: [pictures: { methods: [:display_url] }])
  end
end

app/helpers/event_helper.rb
module EventHelper
  include LinkHelper

  def combine_events_with_carousel_items(events, carousel_items)
    event_carousel_items = events.collect { |event| convert_event_to_carousel_item(event) }

    # Combine the carousel items into one array.
    event_carousel_items + carousel_items
  end

  def convert_event_to_carousel_item(event)
    url = url_for(event)
    {
      title: event.name_and_author,
      tagline: "<small>#{event.date_and_price}</small><br>#{event.short_blurb}".html_safe,
      image: event.fetch_image,
      url: url
    }
  end
end

app/views/admin/events/_basic_form.erb
<%# locals: (f:) %>

<% # Looks for an input tagged with event_name and an input tagged with event_slug %>
<%= javascript_include_tag 'name_to_slug.js', defer: true %>

<%= f.input :name, input_html: { id: 'event_name' } %>

<%= f.input :tagline %>

<%= f.input :slug, input_html: { id: 'event_slug' } %>

<%= render 'shared/form/file_field', f: f, field_name: :image, hint: 'This is the image that appears in the slideshow on the frontpage, and as the header image on your event page. The apect ratio should be approximately 48/25.' %>

<%= f.input :start_date, start_year: Rails.configuration.start_year, end_year: max_end_year %>

<%= f.input :end_date, start_year: Rails.configuration.start_year, end_year: max_end_year %>

<%= f.association :venue, collection: Venue.all, label_method: :name, required: true %>

<%= f.input :author, collection: Event.author_name_list, allow_custom_input: true %>

<%= f.input :price %>

<% unless f.object.is_a? Season %>
  <% if f.object.persisted? %>
    <%= f.association :season, collection: f.object.simultaneous_seasons, label_method: :name %>
  <% else %>
    <p>You can add a season after adding the event.</p>
  <% end %>
<% end %>

<%= f.association :proposal, collection: f.object.possible_proposals, label_method: :show_title %>

<%= f.input :is_public, hint: 'Display this event on the publicly visible part of the website?' %>

<%= render 'admin/events/event_tags_form_section', f: f %>

<%= render "/shared/form/md_editor", f: f, field: :publicity_text %>

<%= render "/shared/form/md_editor", f: f, field: :content_warnings %>

<%= render "/shared/form/md_editor", f: f, field: :members_only_text %>

<%= render '/shared/form/sections/gallery', f: f %>

<%= render 'shared/form/sections/attachments', f: f %>

<%= render 'shared/form/sections/video_links', f: f %>

<%= render layout: '/shared/collapsible_section', locals: { title: 'Pretix Widget Configuration' } do %>
    <%= f.input :pretix_shown, hint: 'Display the Pretix widget for this event.' %>
    <%= f.input :pretix_slug_override, hint: ' Leave blank to use the slug for this event as the Pretix slug' %>
    <%= f.input :pretix_view, collection: ['list','week','month'], default: 'list', hint: "See Pretix's documentation for examples" %>
  </div>
<% end %>

app/views/admin/events/_basic_show.erb
<%# locals: (event:, extra_fields: {}) %>

<% # I cannot guarantee that all of these if's are properly tested (all cases being hit), so be careful when modifying %>

<% # Note: If you update the ransack search form, this has some things with q that need to be changed. %>

<%= content_for :publicity_and_members do %>
  <div class="row vertical-rule">
    <div class="col-<%= event.team_members.any? ? 'xl-6' : '12' %>">
      <h3>Publicity Text</h3>
      <%= render_markdown event.publicity_text %>
    </div>

    <% if event.team_members.any? %>
      <div class="col-xl-6">
          <%= render '/shared/admin_show_team_members', team_members: event.team_members %>
      </div>
    <% end %>
  </div>
<% end %>

<% fields = { 
  slug:           event.slug,
  'ID' =>         (event.id if can?(:manage, event)),
  'SparkSeat Slug' => (event.spark_seat_slug if event.spark_seat_slug.present?),
  'XTS ID' =>     (event.xts_id if event.xts_id.present?),
  is_public:      bool_text(event.is_public),
  proposal:       'No proposal linked',
  season:         event.season.present? ? get_link(event.season, :show) : 'Not part of a season',
  author:         event.author.present? ? link_to(event.author, admin_events_url('q[author_cont]' => event.author)) : 'No author specified',
  'Date(s)' =>    event.date_range(true),
  venue:          event.venue.present? ? link_to(event.venue.name, admin_events_url('q[venue_id_eq]' => event.venue.id)) : 'No Venue specified',
  price:          event.price,
  tagline:        event.tagline.presence || 'No tagline',
  event_tags:     event.event_tags.accessible_by(current_ability).collect{ |event_tag| link_to(event_tag.name, admin_events_url('q[event_tags_id_eq]' => event_tag.id))}.join('; ').presence&.html_safe() || 'There are no tags set for this event.',
  image:          { type: 'image', image: event.image, variant: slideshow_variant },
  publicity_and_members: { type: 'content', content: yield(:publicity_and_members) },
  content_warnings: { type: 'content', markdown: event.content_warnings },
  members_only_text: { type: 'markdown', markdown: event.members_only_text },
  gallery:        { type: 'content', content: render('/shared/gallery', pictures: event.pictures.accessible_by(current_ability, :show)) },
  attachments:    { type: 'content', content: render('shared/attachments_gallery', attachments: event.all_attachments.accessible_by(current_ability, :show)) },
  video_links:    { type: 'content', content: render('shared/video_link_gallery', video_links: event.video_links.accessible_by(current_ability, :show)) },
  questionnaires: { type: 'content', content: render('admin/events/questionnaires', event: event) }
} %>

<% # Proposal %>
<% if event.proposal.present? && can?(:view, event.proposal) %>
  <% fields[:proposal] = get_link(event.proposal, :show, link_target: admin_proposals_proposal_path(event.proposal)) %>
<% end %>

<% fields = fields.merge(extra_fields) %>

<% content_for :extra_show_actions do %>
  <%= view_page_on_main_site_button if event.is_public %>
  <%= get_link event, :edit, link_text: "Bulk Import Team", link_target: new_admin_show_show_crew_import_path(event)%>
<% end %>

<%= render('shared/pages/show', object: event, fields: fields) %>

app/views/admin/events/_debt_settings_form.erb
<p>
    Configure the number of debts to assign to team members. Once configured, debts will be
    automatically created when team members are added to the <%= event.class.name.downcase %>. Saving these settings will
    also sync debts for all existing team members.
</p>
<p>
    <strong>Position rules:</strong> Assistants (all roles must be assistant) get max 1 staffing debt.
    Welfare contacts (if their only role) get 0 staffing debts.
</p>

<% if event.tag_debt_recommendations.any? %>
    <div class="alert alert-info">
        <strong>Tag recommendations:</strong>
        <% event.tag_debt_recommendations.each do |rec| %>
            <div>
                Tag "<%= rec[:tag_name] %>":
                <%= rec[:maintenance] || 0 %> maintenance,
                <%= rec[:staffing] || 0 %> staffing
            </div>
        <% end %>
    </div>
<% end %>

<%= simple_horizontal_form_for event, url: polymorphic_path([:update_debt_settings, :admin, event]), method: :patch do |f| %>
    <%= f.error_notification %>

    <div class="row">
        <div class="col-md-6">
            <h5>Maintenance Debts</h5>
            <%= f.input :maintenance_debt_amount, label: 'Amount per person', as: :integer, min: 0, max: 5,
                        hint: 'Leave blank or set to 0 to disable auto-creation' %>
            <%= f.input :maintenance_debt_start, as: :date, label: 'Due date',
                        default: ((event.end_date || Date.current) + 14) %>
        </div>
        <div class="col-md-6">
            <h5>Staffing Debts</h5>
            <%= f.input :staffing_debt_amount, label: 'Amount per person', as: :integer, min: 0, max: 5,
                        hint: 'Leave blank or set to 0 to disable auto-creation' %>
            <%= f.input :staffing_debt_start, as: :date, label: 'Due date',
                        default: ((event.end_date || Date.current) + 14) %>
        </div>
    </div>

    <%= f.button :submit, value: 'Save Debt Settings', class: 'btn btn-primary' %>
<% end %>

<% if event.debt_configuration_active? %>
    <hr>
    <p class="text-muted">
        <strong>Current configuration:</strong>
        <%= event.maintenance_debt_amount.present? ? "#{event.maintenance_debt_amount} maintenance debt(s)" : "No maintenance debts" %>
        &bull;
        <%= event.staffing_debt_amount.present? ? "#{event.staffing_debt_amount} staffing debt(s)" : "No staffing debts" %>
    </p>
<% end %>

app/views/admin/events/_event_tags_form_section.erb
<%# locals: (f:) %>

<div class="form-horizontal">
  <h3>Tags</h3>

<% if f.object.event_tags.empty? %>
  <div id="no_event_tags_warning" class="alert alert-danger">
  You have not set any tags for this Event.
  </div>
<% end %>

<%= f.association(:event_tags, collection: EventTag.accessible_by(current_ability), input_html: { multiple: 'multiple' }) %>

app/views/admin/events/_questionnaires.erb
<%# locals: (event:) %>

<% questionnaires = event.questionnaires.accessible_by(current_ability) %>

<% if questionnaires.any? { |questionnaire| can?(:show, questionnaire) } %>
    <h3>Questionnaires</h3>

    <table class="table">
      <tbody>
        <% questionnaires.each do |questionnaire| %>
            <tr>
              <%= get_link questionnaire, :answer, http_method: :get, html_class: '', append_name: true, wrap_tag: 'td' %>   

              <%= get_link questionnaire, :show, prefix: 'View', append_name: cannot?(:answer, questionnaire), 
                           html_class: ('btn btn-secondary' if can?(:answer, questionnaire)), wrap_tag: 'td' 
              %>

              <%= get_link questionnaire, :edit, wrap_tag: 'td' %>
            </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

<%= get_link Admin::Questionnaires::Questionnaire, :new, 
             html_class: (questionnaires.empty? ? 'btn btn-secondary' : 'btn btn-primary'), 
             link_target: new_admin_questionnaires_questionnaire_url(event_id: event.id), 
             additional_condition: event.end_date > Date.current 
%>

app/views/admin/events/_review_fields.erb
<%# locals: (f:, dynamic: nil) %>

<%- # Mind that there is also an actual form to edit and create reviews. %>
<div class="control-group fields">
    <%= render('admin/reviews/review_fields', f: f) %>

    <%= link_to_remove f %>
    <hr />
</div>

app/views/admin/events/_reviews.erb
<%# locals: (reviews:) %>

<% if reviews.any? %>
  <div class="row row-cols-auto g-3 row-cols-1 <%= 'row-cols-lg-2' if reviews.count > 1 %> ">
    <% reviews.each do |review| %>
      <div class="col">
        <div class="card h-100">
            <div class="card-header">
              <h4>
                <%= review.title %><%= " - <span class=\"no-wrap\">#{star_rating(review.rating)}</span>".html_safe %>
              </h4>
            </div>
          
          <div class="card-body">
            <p class="card-text"><small class="text-muted"><%= l review.review_date, format: :long %><%= " - By #{review.reviewer_with_organisation}"%></small></p>

            <%= render_markdown review.body %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/events/_reviews_form_partial.erb
<%# locals_binary_0.5: (f:) %>

<%= render layout: '/shared/collapsible_section', locals: { title: 'Reviews' } do %>
  <%= render('shared/form/sections/nested_fields', f: f, association_name: :reviews, partial_name: 'admin/events/review_fields') %>
<% end %>

app/views/admin/events/debt_overview.html.erb
<h1>Debt Overview</h1>

<p class="text-muted">
  Shows in the current academic year and future. Color-coded to help identify which shows need debt configuration.
</p>

<div class="mb-3">
  <span class="badge bg-warning text-dark">Yellow</span> = Has tags with debt recommendations but no debts configured<br>
  <span class="badge bg-danger">Red</span> = Has debts configured that don't match tag recommendations<br>
  <span class="badge bg-success">Green</span> = Debts match tag recommendations
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Show</th>
        <th>Dates</th>
        <th>Tags</th>
        <th>Maintenance Debts</th>
        <th>Staffing Debts</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @shows.each do |show| %>
        <tr class="<%= debt_status_row_class(show) %>">
          <td>
            <%= get_link show, :show %>
          </td>
          <td>
            <%= show.date_range(true, :short) %>
          </td>
          <td>
            <% if show.event_tags.any? %>
              <% show.event_tags.each do |tag| %>
                <span class="badge bg-secondary"><%= tag.name %></span>
              <% end %>
            <% else %>
              <span class="text-muted">No tags</span>
            <% end %>
          </td>
          <td>
            <% if show.maintenance_debt_amount.present? %>
              <strong><%= show.maintenance_debt_amount %></strong>
              <% if show.maintenance_debt_start.present? %>
                (due <%= show.maintenance_debt_start.strftime("%d %b %y") %>)
              <% end %>
            <% else %>
              <span class="text-muted">Not configured</span>
            <% end %>
          </td>
          <td>
            <% if show.staffing_debt_amount.present? %>
              <strong><%= show.staffing_debt_amount %></strong>
              <% if show.staffing_debt_start.present? %>
                (due <%= show.staffing_debt_start.strftime("%d %b %y") %>)
              <% end %>
            <% else %>
              <span class="text-muted">Not configured</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'Configure', admin_show_path(show, anchor: 'debt_settings'), class: 'btn btn-sm btn-primary' %>
          </td>
        </tr>
        <% if show_debt_recommendation_details?(show) %>
          <tr class="<%= debt_status_row_class(show) %>">
            <td colspan="6" class="small">
              <em>Tag recommendations:
                <% show.tag_debt_recommendations.each do |rec| %>
                  <%= rec[:tag_name] %>: <%= rec[:maintenance] || 0 %> maintenance, <%= rec[:staffing] || 0 %> staffing &nbsp;
                <% end %>
              </em>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<% if @shows.empty? %>
  <div class="alert alert-info">
    No shows found in the current academic year or future.
  </div>
<% end %>

app/views/admin/events/index.html.erb
<% 
headers = [:name, :start_date, :tagline]

field_sets = @events.map { |event| { 
  fields: [
    event,
    event.date_range(true, :short),
    event.short_blurb
  ] } }

if current_user.present? && current_user.has_role?('Member')
  members_only_text_entry = { slug: 'defaults.members_only_text' }
else
  members_only_text_entry = nil
end

# Essentially the same as in the public events index, so likely edit that too if you edit this.
search_fields = {
  name_cont:                      { slug: 'defaults.name' },
  publicity_text_or_tagline_cont: { slug: 'defaults.publicity_text' },
  members_only_text_cont:         members_only_text_entry,
  users_full_name_cont:           { slug: 'defaults.user' },
  author_cont:                    { slug: 'defaults.author' },

  venue_id_eq:                    { slug: 'defaults.venue', type: :select, collection: Venue.accessible_by(current_ability) },
  event_tags_id_eq:               { slug: 'defaults.event_tags', type: :select, collection: EventTag.accessible_by(current_ability) },
  date_range:                     { type: :date_range, options: {  start_date_attribute: 'start_date', end_date_attribute: 'end_date'} },
  show_private_only:              { slug: 'defaults.show_private_only', type: :boolean },

  random_button:      { type: :submit_button, action: :Random },
  on_this_day_button: { type: :submit_button, action: 'On This Day' }
}

quick_actions = []
if @events.klass == Show && can?(:debt_overview, Event)
  quick_actions << link_to('Show Debt Overview', debt_overview_admin_events_path, class: 'btn btn-primary')
end
%>

<%= render 'shared/pages/index', resource_class: @events.klass, resources: @events, headers: headers, field_sets: field_sets, search_fields: search_fields,
  show_new_button: @events.klass != Event, quick_actions: quick_actions %>