config/routes.rb
require "silencer"

ChaosRails::Application.routes.draw do
  devise_for :users

  use_doorkeeper
  use_doorkeeper_openid_connect

  root to: "static#home"

  match "*path", to: "application#options", via: :options

  get "up" => "rails/health#show", as: :rails_health_check

  resources :events,      only: [ :index ]
  resources :shows,       only: [ :index, :show ]
  resources :workshops,   only: [ :index, :show ]
  resources :seasons,     only: [ :index, :show ]
  resources :news,        only: [ :index, :show ]
  resources :venues,      only: [ :index, :show ] do
    collection do
      get "map"
    end
  end

  resource :profile_completion, only: [ :show, :update ]

  resources :users, only: [ :show ] do
    member do
      put "consent"
    end

    collection do
      get "current", to: "users#current"
    end
  end

  get "marketing_creatives/sign_up", to: "admin/marketing_creatives/profiles#sign_up"

  COMPLAINTS_ALIASES.each do |path|
    get path, to: redirect("complaints/new")
  end

  resources :complaints, only: [ :new, :create ]

  get "attachments/:slug(/:style)", to: "attachments#file", as: "attachment"

  if Rails.env.test? || Rails.env.development?
    get "tests/test_500", to: "tests#test_500"
  end

  namespace :admin do
    get "", to: "dashboard#index"

    mount MissionControl::Jobs::Engine, at: "/jobs"

    get "resources", to: "resources#page", as: :resources_index
    get "resources/membership_checker", to: "resources#membership_checker", as: :resources_membership_checker
    get "resources/(*page)", to: "resources#page", as: :resources

    resources :events, only: [ :index, :show ] do
      member do
        get "xts", to: "events#find_by_xts_id"
      end

      collection do
        get "debt_overview"
      end
    end

    resources :shows do
      resources :feedbacks, except: [ :show ]

      resources :show_crew_imports, only: [ :new ] do
        collection do
          post :preview
          post :confirm
        end
      end

      collection do
        get "query_xts"
      end

      member do
        patch "update_debt_settings", to: "shows#update_debt_settings"
        get "xts_report"
        post "convert_to_season", to: "shows#convert_to_season"
        post "convert_to_workshop", to: "shows#convert_to_workshop"
      end
    end

    resources :workshops do
      resources :feedbacks, except: [ :show ]

      resources :show_crew_imports, only: [ :new ] do
        collection do
          post :preview
          post :confirm
        end
      end

      member do
        patch "update_debt_settings", to: "workshops#update_debt_settings"
      end
    end

    resources :seasons do
      resources :feedbacks, except: [ :show ]

      resources :show_crew_imports, only: [ :new ] do
        collection do
          post :preview
          post :confirm
        end
      end

      member do
        patch "update_debt_settings", to: "seasons#update_debt_settings"
      end
    end

    resources :debt_notifications, only: [ :index ]

    resources :staffing_debts, except: [ :destroy ] do
      member do
        put "convert_to_maintenance_debt"
        put "forgive"
      end
    end

    resources :maintenance_debts, except: [ :destroy ] do
      member do
        put "convert_to_staffing_debt"
        put "forgive"
      end
    end

    resources :debts

    resources :maintenance_sessions
    resources :maintenance_attendances

    resources :venues do
      collection do
        get "map"
      end
    end

    resources :news
    resources :fault_reports

    resources :event_tags
    resources :attachment_tags
    resources :picture_tags

    resources :attachments, only: [ :index ]
    resources :pictures, only: [ :index ]

    resources :opportunities do
      member do
        put "approve"
        put "reject"
      end
    end

    resources :membership, only: [] do
      collection do
        get "check_membership", to: "membership#check_membership"
      end
    end

    resources :editable_blocks
    resources :carousel_items
    resources :mass_mails

    resources :users do
      member do
        post "reset_password"
        get "merge"
        post "merge_preview"
        post "absorb"
      end

      collection do
        get  "activate", to: "users#activate"
        post "activate", to: "users#create_activation"
        post "resend_activation", to: "users#resend_activation"
        get  "autocomplete_list", constraints: { format: :json }
      end
    end

    resources :duplicates, only: [ :index ] do
      collection do
        post :mark_not_duplicate
      end
    end

    resources :membership_imports, only: [ :new ] do
      collection do
        post :preview
        post :confirm
      end
    end

    resources :user_imports, only: [ :new ] do
      collection do
        post :preview
        post :confirm
      end
    end

    resources :reviews

    resources :roles do
      member do
        post "add_user", to: "roles#add_user"
        delete "remove_user/:user_id", to: "roles#remove_user", as: "remove_user"
        delete "purge", to: "roles#purge"
        put "archive", to: "roles#archive"
      end
    end

    get  "/permissions/grid", to: "permissions#grid", as: :permissions
    post "/permissions/grid", to: "permissions#update_grid", as: :update_permissions

    resources :techies do
      collection do
        get "tree"
        get "bush"
        get "tree_data"
        get "mass_new"
        post "mass_create"
        get "by_entry_year"
      end
    end

    get "techie_families", to: "techies#index"

    namespace :marketing_creatives do
      resources :profiles do
        collection do
          get "sign_up", to: "profiles#sign_up"
        end

        member do
          put "approve"
          put "reject"
        end
      end

      resources "", controller: "categories", as: "categories"
    end

    resources :staffing_templates

    resources :staffings do
      collection do
        get ":slug/grid", to: "staffings#grid", format: :html, as: :grid
      end
    end

    get "/staffings/job/:id/sign_up_confirm", to: "staffings#sign_up_confirm", as: :sign_up_confirm
    put "/staffings/job/:id/sign_up", to: "staffings#sign_up", as: :staffing_sign_up

    get "/proposals", to: redirect("/admin/proposals/calls")
    namespace :proposals do
      resources :calls do
        member do
          put "archive"
        end

        resources :proposals, only: :index
      end

      resources :proposals, except: :index do
        member do
          put "approve"
          put "reject"
          put "convert"
        end
      end

      get "/about", to: "proposals#about"
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires do
        member do
          get  "answer", to: "questionnaires#answer"
          put "answer", to: "questionnaires#set_answers"
          patch "answer", to: "questionnaires#set_answers"
        end
      end

      resources :questionnaire_templates
    end

    get "tests", to: "tests#index"
    namespace :tests do
      get "test_alerts/:type", action: "test_alerts", as: "test_alerts"
      get "test_404"
      get "test_500"
      get "test_access_denied"
    end

    resources :complaints, except: [ :new, :create ] do
      get "new", to: redirect("/complaints/new")
    end

    get "/reports/", to: "reports#index", as: "reports"
    namespace "reports" do
      %w[roles members newsletter_subscribers staffing].each do |action|
        put action, action: action, as: action
      end
    end

    namespace "help" do
      %w[kramdown venue_location].each do |action|
        get action, action: action, as:  action, controller: "/admin/help"
      end
    end

    get "committee", to: "static#committee", as: :committee
    get "bootstrap_test", to: "static#bootstrap_test", as: :bootstrap_test
    get "*page", to: "static#error", as: :static

    if Rails.env.test? || Rails.env.development?
      get "dashboard/widget/:widget_name", to: "dashboard#widget"
    end
  end

  get "archives", to: "archives#index", as: :archives_index
  namespace :archives do
    get "events", to: "events#index", as: :events
    get "shows", to: "shows#index", as: :shows
    get "workshops", to: "workshops#index", as: :workshops
    get "proposals", to: "proposals#index", as: :proposals
    get "seasons",    to: "seasons#index",    as: :seasons
  end
  get "archives/(*page)", to: "archives#page", as: :archives

  post "markdown/preview", to: "markdown#preview"

  get "about", to: "about#page", as: :about_index
  get "about/(*page)", to: "about#page", as: :about

  get "get_involved", to: "get_involved#page", as: :get_involved_index
  get "get_involved/opportunities", to: "get_involved#opportunities", as: :get_involved_opportunities
  get "get_involved/(*page)", to: "get_involved#page", as: :get_involved

  get "youth", to: redirect("/getinvolved/youth_project")

  get "welcomeweek", to: redirect("/welcome_week")
  get "welcome_week/parapicnic_in_the_park", to: redirect("https://theatreparadok.co.uk/events/2021_09_parapicnic/")
  get "welcome_week/catching_up", to: redirect("https://theatreparadok.co.uk/events/catching-up-fringe-show-performance-screening-for-welcome-week/")

  get "welcome_week", to: redirect("get_involved/welcome_week")

  get "dev_auth/login", to: "dev_auth#login" if Rails.env.local?

  get "/:id", to: "seasons#show", constraints: Constraints::ExistingSeason.new

  get "/*page", to: "static#show", as: :static, constraints: lambda { |request|
    !request.path.starts_with?("/rails/active_storage") && !request.path.starts_with?("/assets")
  }

end

app/controllers/admin/techies_controller.rb
##
# Responsible for the techie family tree.
##
# Source for some of the tree: https://gist.github.com/markjlorenz/3744338
class Admin::TechiesController < AdminController
  include GenericController

  load_and_authorize_resource except: [ :tree, :bush, :mass_new, :mass_create, :by_entry_year ]

  def show
    super

    @coparents = @techie.children.flat_map(&:parents).uniq - [ @techie ]
  end

  def bush
    authorize! :index, Techie

    @q = Techie.ransack(params[:q], auth_object: current_ability)

    @title = "Techie Family Tree - New but sucks"
  end

  def tree_data
    nodes = @techies.select(:id, :name)
    edges = @techies.includes(:children).flat_map { |techie| techie.children.ids.uniq.map { |child_id| [ techie.id, child_id ] } }

    json = { edges: edges, nodes: nodes }.to_json

    render json: json
  end

  # Remember to remove Dracula and stuff when you finally get rid of this one.
  def tree
    authorize! :index, Techie

    @title = "Techie Family Tree"

    @q = Techie.ransack(params[:q], auth_object: current_ability)

    include_siblings_of_related = false
    amount_of_generations = 10

    @base_techie = @q.result(distinct: true)

    if @base_techie.size == 1
      @techies = @base_techie.first.get_relatives(amount_of_generations, include_siblings_of_related)
    else
      @techies = @base_techie.includes(:children, :parents)
    end
  end

  def mass_new
    authorize! :new, Techie
  end

  def mass_create
    authorize! :create, Techie

    relationships_data = params[:techie][:relationships_data]

    if Techie.mass_create(relationships_data)
      helpers.append_to_flash(:success, "The mass create of techies was successfull.")

      redirect_to(admin_techies_url)
    else
      render "mass_new", status: :unprocessable_entity
    end
  end

  def by_entry_year
    authorize! :index, Techie

    @title = "Techies by Entry Year and Parents"

    # Get all techies with their parents and children, grouped by entry year
    @techies_by_year = Techie.includes(:parents, :children)
                            .where.not(entry_year: nil)
                            .group_by(&:entry_year)
                            .sort.reverse.to_h

    # Get techies without entry year
    @techies_without_year = Techie.includes(:parents, :children)
                                 .where(entry_year: nil)

    # Process each year to group techies by parent combinations
    @grouped_data = {}
    @techies_by_year.each do |year, techies|
      @grouped_data[year] = group_techies_by_parents(techies)
    end

    # Process techies without entry year
    @grouped_no_year = group_techies_by_parents(@techies_without_year)
  end

  private

  def permitted_params
    [ :name, :entry_year, children_attributes: [ :id, :_destroy, :name ], parents_attributes: [ :id, :_destroy, :name ] ]
  end

  def order_args
    [ "name asc", "entry_year asc" ]
  end

  def group_techies_by_parents(techies)
    # Group techies by their parent combinations
    grouped = {}

    techies.each do |techie|
      parent_names_with_years = techie.parents.map(&:name_with_entry_year).sort
      parent_key = parent_names_with_years.empty? ? "No Parents" : parent_names_with_years.join(" & ")

      grouped[parent_key] ||= []
      grouped[parent_key] << techie
    end

    # Sort by parent group names alphabetically and sort techies within each group
    grouped.sort.map do |parent_key, group_techies|
      [ parent_key, group_techies.sort_by(&:name) ]
    end.to_h
  end
end

app/views/admin/techies/_child_fields.erb
<%# locals: (f:, dynamic: nil) %>

<%= render('relation_fields', f: f) %>

app/views/admin/techies/_form.html.erb
<%# locals: () %>

<%= simple_horizontal_form_for [:admin, @techie] do |f| %>
  <%= render('shared/pages/form', f: f) do %>
    <%= f.input :name %>
    <%= f.input :entry_year %>
    
    <%- # parent_fields and child_fields are a wrapper around relations_field that needs to exist so link_to_add works properly. %>

    <h3>Parents</h3>
    <%= render('shared/form/sections/nested_fields', f: f, association_name: :parents, partial_name: 'parent_fields') %>

    <h3>Children</h3>
    <%= render('shared/form/sections/nested_fields', f: f, association_name: :children, partial_name: 'child_fields') %>
  <% end %>
<% end %>

app/views/admin/techies/_parent_fields.erb
<%# locals: (f:, dynamic: nil) %>

<%= render('relation_fields', f: f) %>

app/views/admin/techies/_relation_fields.erb
<%# locals: (f:, dynamic: nil) %>

<%= render '/shared/form/inline_fields_for_template',
    f: f,
    fields: [
        { field: f.input_field(:id, collection: Techie.where.not(id: @techie.id), wrapper: :inline_form) },
        { field: link_to_remove(f), col_modifier: 'auto' }
] %>

app/views/admin/techies/bush.erb
<% content_for :head do %>
  <style type='text/css'>
    svg,
    #graph-container {
      width: 500px; 
      height: 500px;
      border:1px solid green;
      background-color: #CCC;

    }
  </style>
<% end %>

<div>
  <%= get_link Techie, :index, html_class: 'btn btn-primary' %>

  <%= get_link Techie, :new, html_class: 'btn btn-secondary' %>
</div>

<div class="row">
    <div class="span12">
        <%= search_form_for @q, builder: SimpleForm::FormBuilder, url: :tree_admin_techies, html: { id: 'search', class: 'form-search form-inline'} do |f| %>
            <%= f.select :id_eq, options_from_collection_for_select(Techie.all, "id", "name", @q.id_eq), include_blank: true %>

            <%= f.submit :Search, class: 'btn btn-secondary' %>
        <% end %>
    </div>
</div>

<div id="techie-tree-container"></div>

app/views/admin/techies/by_entry_year.html.erb
<% quick_actions = [
  link_to(generate_icon_prefix('list', 'All Techies'), admin_techies_url, class: 'btn btn-secondary'),
  link_to(generate_icon_prefix('tree', 'Tree'), tree_admin_techies_url, class: 'btn btn-secondary'),
  link_to(generate_icon_prefix('user-group', 'Mass Add Techies'), mass_new_admin_techies_url, class: 'btn btn-secondary'),
] %>

<div class="row">
  <div class="col">
    <% unless quick_actions.blank? %>
      <div class="card">
        <div class="card-header">
          <span class="card-title">Quick actions</span>
        </div>
        <div class="card-body">
          <% quick_actions.each do |quick_action| %>
            <%= quick_action %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <span class="card-title"><%= @title %></span>
      </div>
      <div class="card-body">
        <% if @grouped_data.empty? && @grouped_no_year.empty? %>
          <p class="text-muted">No techies found.</p>
        <% else %>
          <% @grouped_data.each do |year, parent_groups| %>
            <div class="mb-4">
              <h3 class="text-primary"><%= year %></h3>

              <% if parent_groups.empty? %>
                <p class="text-muted ms-3">No techies found for this year.</p>
              <% else %>
                <% parent_groups.each do |parent_group, techies| %>
                  <div class="ms-3 mb-3">
                    <h5 class="text-secondary mb-2"><%= parent_group %>:</h5>
                    <ul class="ms-3">
                      <% techies.each do |techie| %>
                        <li><%= link_to techie.name, admin_techie_path(techie), class: 'text-decoration-none' %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>

          <% unless @grouped_no_year.empty? %>
            <div class="mb-4">
              <h3 class="text-secondary">No Entry Year</h3>

              <% @grouped_no_year.each do |parent_group, techies| %>
                <div class="ms-3 mb-3">
                  <h5 class="text-secondary mb-2"><%= parent_group %>:</h5>
                  <ul class="ms-3">
                    <% techies.each do |techie| %>
                      <li><%= link_to techie.name, admin_techie_path(techie), class: 'text-decoration-none' %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/techies/index.html.erb
<% quick_actions = [
  link_to(generate_icon_prefix('calendar', 'By Entry Year'), by_entry_year_admin_techies_url, class: 'btn btn-secondary'),
  link_to(generate_icon_prefix('tree', 'Tree'), tree_admin_techies_url, class: 'btn btn-secondary'),
  link_to(generate_icon_prefix('user-group', 'Mass Add Techies'), mass_new_admin_techies_url, class: 'btn btn-secondary'),
] %>

<% headers = [:name, :entry_year] %>

<% field_sets = @techies.map { |techie| {fields: [techie, techie.entry_year] } } %>

<% search_fields = { name_cont: { slug: 'defaults.name' }, entry_year_eq: { slug: 'defaults.entry_year' } } %>

<%= render 'shared/pages/index', resource_class: Techie, resources: @techies, headers: headers, field_sets: field_sets, search_fields: search_fields,
  quick_actions: quick_actions %>

app/views/admin/techies/mass_new.html.erb
<%= simple_horizontal_form_for :techie, url: mass_create_admin_techies_url do |f| %>
  <%= render('shared/pages/form', f: f) do %>
    <p>
        To add multiple techies at once, enter the data in the following format. One 'family' per line:<br>
       (name of parent 1), (name of parent 2), (etc etc) &gt; (name of child 1), (name of child 2), (etc etc)
    </p>
    <p>
        For example:<br>
        Alice, Bob &gt; Charlie, Derek, Elise<br>
        Alice, &gt; Francis, George
    </p>
    <p>
    <b>Make sure that you use the exact names of the existing techies as they appear in the index, or you will create duplicate techies, which is messy!</b>
    </p>
    <%= f.input :relationships_data, as: :text, input_html: { rows: 20 } %>
  <% end %>
<% end %>

app/views/admin/techies/show.html.erb
<% content_for :parents do %>
  <ul>
    <% @techie.parents.each do |parent| %>
      <li><%= link_to parent.name_with_entry_year, admin_techie_path(parent) %></li>
    <% end %>
  </ul>
<% end %>

<% content_for :children do %>
  <% children_by_year = @techie.children.group_by(&:entry_year).sort_by { |year, children| year || Float::INFINITY }.reverse %>
  <% children_by_year.each do |year, children| %>
    <div class="mb-3">
      <h6 class="text-secondary"><%= year ? year : "No Entry Year" %></h6>
      <ul>
        <% children.sort_by(&:name).each do |child| %>
          <li><%= get_link child, :show %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<% content_for :co_parents do %>
  <ul>
    <% @coparents.each do |coparent| %>
      <li><%= link_to coparent.name_with_entry_year, admin_techie_path(coparent) %></li>
    <% end %>
  </ul>
<% end %>

<% fields = { entry_year: @techie.entry_year } %>
<% [:parents, :children, :co_parents].each { |relation| fields[relation] = { type: 'content', header: relation.to_s.dasherize.titleize, content: yield(relation) } } %>

<%= render('shared/pages/show', object: @techie, fields: fields) %>

app/views/admin/techies/tree.erb
<% content_for :head do %>
    <%= javascript_include_tag 'raphael-min.js', defer: true %>
    <%= javascript_include_tag 'dracula_graffle.js', defer: true %>
    <%= javascript_include_tag 'dracula_graph.js', defer: true %>
<% end %>

<%= render('shared/quick_actions_card') do %>
  <%= get_link Techie, :index, html_class: 'btn btn-primary' %>
  <%= get_link Techie, :new, html_class: 'btn btn-secondary' %>
<% end %>

<div class="row">
    <div class="col">
        <%= search_form_for @q, builder: SimpleForm::FormBuilder, url: :tree_admin_techies, html: { id: 'search', class: 'form-search form-inline mt-3'} do |f| %>
            <% #= f.select :id_eq, options_from_collection_for_select(Techie.all, "id", "name", @q.id_eq), include_blank: true %>
            <%= f.input :id_eq, collection: Techie.all.select('id', 'name'), include_blank: true, label: 'Techie Name' %>
            <div class="mr-2"></div>
            <%= f.submit :Search, class: 'btn btn-secondary' %>
        <% end %>
    </div>
</div>

<div id="canvas" style="width: 940px; height: 1500px;"></div>
<script defer>
    document.addEventListener('DOMContentLoaded', function () {

var g = new Graph();

var render = function(renderer, node) {
        /* the Raphael set is obligatory, containing all you want to display */
        var text = renderer.text(node.point[0] + 10, node.point[1] + 10, node.label);
        var dimensions = text.getBBox();

        var set = renderer.set().push(
            /* custom objects go here */
            renderer.rect(node.point[0] - (dimensions.width)/2, node.point[1], dimensions.width + 20, dimensions.height + 10).attr({"fill": "#feb", r : "12px", "stroke-width" : node.distance == 0 ? "3px" : "1px" })).push(
              text
            );

        text.toFront();
        return set;
    };

/* add a simple node */
<% @techies.each do |techie| %>
g.addNode("<%= techie.id %>", { render:render, label: "<%= techie.name.html_safe %>" });
<% end %>

<% @techies.each do |techie| %>
    <% techie.children.each do |child| %>
        <% if @techies.include?(child) %>
            g.addEdge("<%= techie.id %>", "<%= child.id %>", {directed: true});
        <% end %>
    <% end %>
<% end %>

/* layout the graph using the Spring layout implementation */
var layouter = new Graph.Layout.Spring(g);
layouter.layout();

/* draw the graph using the RaphaelJS draw implementation */
var renderer = new Graph.Renderer.Raphael('canvas', g, 940, 1500);
renderer.draw();

});
</script>